version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/myapp   # your app directory on EC2

file_exists_behavior: OVERWRITE

hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 60
      runas: root

  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 120
      runas: root

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
      runas: root
